name: monetization
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^2.3.0
  get: ^4.6.5
  intl: ^0.17.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^9.5.3+1
  url_strategy: ^0.2.0
  http: ^0.13.5
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3
  html: ^0.15.1
  jiffy: ^5.0.0
  youtube_player_flutter: ^8.1.1
  share_plus: ^6.3.0
  sqflite: ^2.2.2
  flutter_widget_from_html_core: ^0.9.0+2
  flutter_inappwebview: ^5.7.2+3
  webview_flutter: ^4.0.1
  webview_flutter_wkwebview: ^3.0.1
  webview_flutter_android: ^3.1.1
  shimmer: ^2.0.0
  awesome_notifications: ^0.7.4+1
  app_settings: ^4.1.8
  package_info_plus: ^3.0.2
  r_launch_appstore: ^1.0.1
  in_app_review: ^2.0.6
  get_time_ago: ^1.1.2
  video_player: ^2.4.10
  firebase_analytics: ^10.1.0
  store_checker: ^1.1.0
  photo_view: ^0.14.0
  image_picker: ^0.8.5+3
  image_picker_ios: ^0.8.5+6
  image_compression_flutter: ^1.0.2
  flutter_snake_navigationbar: ^0.6.1
  flutter_blurhash: ^0.7.0
  vibration: 1.7.4-nullsafety.0
  assets_audio_player: ^3.0.6
  universal_html: ^2.0.8
  flutter_widget_from_html: ^0.9.1
  flutter_html: ^3.0.0-alpha.5
  device_info_plus: ^8.0.0
  flutter_masked_text2: ^0.9.1
  scratcher: ^2.3.0
  animated_text_kit: ^4.2.2
  animated_notch_bottom_bar: ^0.0.6
  playing_cards: ^0.3.1+9
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  loading_animation_widget: ^1.2.0+4
  flutter_fortune_wheel: ^1.2.0
  flutter_animated_icons: ^1.0.1
  flutter_switch: ^0.3.2
#  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/icons/
    - assets/language/
    - assets/songs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
